name: workFlow-FirstTry
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  jobb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Hello.py
        run: |
          cd Hello-Github
          python Hello.py